apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharepython-websocket-deployment
  labels:
    app: sharepython-websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sharepython-websocket
  template:
    metadata:
      labels:
        app: sharepython-websocket
    spec:
      containers:
        - name: sharepython-websocket
          image: sharepython-websocket:v.02
          command: ["sh", "-c"]
          args: [
              "
              sanic main.app --host 0.0.0.0 --port 8888
              ",
            ]
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: sharepython-websocket-config
