apiVersion: v1
kind: Service
metadata:
  name: sharepython-api-service
spec:
  type: LoadBalancer
  selector:
    app: sharepython-api
  ports:
    - name: sharepython-api-service-port
      protocol: TCP
      port: 8000
      targetPort: 8000
