apiVersion: v1
kind: Service
metadata:
  name: sharepython-api-service
spec:
  type: NodePort
  selector:
    app: sharepython-api
  ports:
    - name: sharepython-api-service-port
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30009
