apiVersion: v1
kind: Service
metadata:
  name: sharepython-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: sharepython-frontend
  ports:
    - name: sharepython-frontend-service-port
      protocol: TCP
      port: 8080
      targetPort: 80
